# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx2
  name: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      volumes:
        - name: nfs-test-storage
          persistentVolumeClaim:
            claimName: test
      containers:
      - image: nginx:1
        name: nginx
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nfs-test-storage
